SELECT * 
FROM person.Person;

SELECT Title
FROM person.person;

SELECT *
FROM person.EmailAddress;


--A EQUIPE DE MARKETING PRECISA FAZER UMA PEQUISA SOBRE 
--NOMES MAIS COMUNS DE SEUS CLIENTES E PRECISA DO NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESÃO CADASTRADOS
--NO SISTEMA

