SELECT * 
FROM person.Person;

SELECT Title
FROM person.person;

SELECT *
FROM person.EmailAddress;


--A EQUIPE DE MARKETING PRECISA FAZER UMA PEQUISA SOBRE NOMES MAIS COMUNS DE SEUS CLIENTES 
--E PRECISA DO NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESÃO CADASTRADOS
--NO SISTEMA
SELECT firstName, lastName
FROM person.person;


--REMOVER DUPLICADOS DE UMA TABELA. EX.: TINHA 19000 LINHAS COM OS REPETIDOS E USANDO DISTINCT FICOU 1000 E POUCO
SELECT DISTINCT FirstName
FROM person.Person


--##DESAFIO 2
--QUANTOS NOMES SOBRENOMES ÚNICOS TEMOS EM NOSSA TABELA PERSON.PERSON
SELECT DISTINCT LastName
FROM person.Person



-- WHERE

SELECT coluna1, coluna2, coluna_n
FROM tabela
WHERE condicao;

/*
OPERADOR - DESCRIÇÃO
=          IGUAL
>          MAIOR QUE
<          MENOR QUE
>=         MAIOR OU IGUAL
<=         MENOR OU IGUAL
<>         DIFERENTE DE
AND        OPERADOR LOGICO E
OR         OPERADOR LOGICO OU

*/



SELECT *
FROM production.Product
WHERE color = 'blue' or color = 'black'

 

SELECT *
FROM production.Product
WHERE ListPrice > 1500


SELECT *
FROM production.Product
WHERE ListPrice > 1500 and ListPrice < 5000


--COR DIFERENTE DE VERMELHO - NÃO MOSTRA NENHUM COM VERMELHO
SELECT *
FROM production.Product
WHERE color <> 'red'



--DESAFIO! A EQUIPE DE PRODUÇÃO DE PRODUTOS PRECISA DO NOME DE TODAS AS PEÇAS QUE PESAM MAIS QUE 500 KG MAS NÃO
-- MAIS QUE 700 KG PARA INSPEÇÃO
SELECT name
FROM production.Product
WHERE weight > 500 and weight < 700



--DESAFIO! FOI PEDIDO PELO MARKETING UMA RELAÇÃO DE TODOS OS EMPREGADOS (EMPLOYEES) QUE SÃO CASADOS (SINGLE=SOLTERO, MARRIED=CASADO)
--E SÃO ASALARIADOS(SALARIED)
SELECT *
FROM HumanResources.Employee
WHERE MaritalStatus = 'm' AND SalariedFlag = 1



--DESAFIO 3 
-- UM USUARIO CHAMADO PETER KREBS ESTÁ DEVENDO UM PAGAMENTO, CONSIGA O EMAIL DELE PARA QUE POSSAMOS ENVIAR UMA COBRANÇA!
-- (USAR TABELA PERSON.PERSON E DEPOIS TABELA PERSON.EMAILADRESS)
SELECT *
FROM Person.Person
WHERE FirstName = 'peter' and Lastname = 'krebs'

SELECT *
FROM Person.EmailAddress
WHERE BusinessEntityID = 26


--MINUTO 28:06 - 
